spring:
  application:
    name: user-service
  config:
      import: configserver:http://host.docker.internal:8083/config-server/ # This is the crucial line
  cloud:
    config:
      profile: local # Specifies the profile(s) to fetch from the config server
      name: user-service # Application name (should match the config file prefix)
      label: master # Git branch to use
      fail-fast: false # Fail if config server is not available
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1

server:
  address: localhost
  port: 8086
  servlet:
    context-path: /user-service